version: '3'
services:
  nginx:
    image: nginx:1.25.4-bookworm
    ports:
      - 80:80
    volumes:
      - ./web/out:/usr/share/nginx/html
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - web-api-network
  api:
    build: ./api
    volumes:
      - ./api:/var/www/
    networks:
      - web-api-network
      - api-db-network
  db:
    image: postgres:12.18-bookworm
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - api-db-network
      - db-gui-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-gui-network
    depends_on:
      - db

volumes:
  postgres:
networks:
  web-api-network:
    driver: bridge
  api-db-network:
    driver: bridge
  db-gui-network:
    driver: bridge